### PR TITLE
Random enchantment code

### PR DESCRIPTION
**Pull request by ghost**
Credits:
https://www.random.org/clients/http/
http://stackoverflow.com/questions/3559063/how-to-enter-quotes-in-a-java-string
http://20minutemail.com/
http://stackoverflow.com/questions/27190447/pass-json-to-http-post-request
http://www.w3schools.com/
https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js
http://api.jquery.com/jQuery.get/
http://stackoverflow.com/questions/9849754/how-can-i-replace-newlines-line-breaks-with-spaces-in-javascript
Google Chrome Developer Tools

### CODE REVIEW

**Comment by towerofnix** [comment]
wat

**Comment by colt05** [comment]
lololol

**Comment by colt05** [comment]
you can put in a random enchantment code so you have no idea what will happen!

**Comment by towerofnix** [comment]
That's not how the enchantment code chars works :package:

**Comment by colt05** [comment]
ik

**Comment by colt05** [comment]
but if i did it that way, it wouldn't work with more than 1 random number higher than 999 :-1: 
EDIT: nvm now there will be 9 enchantment codes

**Comment by TropicSapling** [comment]
What is this project about? xD

**Comment by towerofnix** [comment]
It "enchants" a message using "death magic".

**Comment by TropicSapling** [comment]
um ok

**Comment by colt05** [comment]
lol

**Pull request closed without merging**
